import { Typography } from "@mui/material";
import React from "react";
import aboutUs from "../assets/images/aboutUs.gif"
import etLogoText from "../assets/images/etLogoText.png"

import { Grid, Box } from '@mui/material';
import stars2 from '../assets/images/stars2.jpg';


const About = () => {

  return (
    <section id="about" style={{
      backgroundImage: `url(${stars2})`, height: "100%", backgroundAttachment: "fixed",
      backgroundPosition: "center",
      backgroundRepeat: "no - repeat",
      backgroundSize: "cover",
    }}>
      <Box mx={2} sx={{ display: "flex", alignItems: "center", flexDirection: "column", justifyContent: "center" }}>
        <Box pb={3} sx={{ maxWidth: "600px", width: "100%", display: "flex", textAlign: "center", flexDirection: "column", justifyContent: "center", borderBottom: "1px solid grey" }}>
          <h1>Earthereum Treasures</h1>
          <p>Earth's Treasures on the Ethereum blockchain.</p>
        </Box>

      </Box>

      <Grid container pt={3} spacing={2} sx={{ alignItems: "center", justifyContent: "center" }}>

        <Grid item xs={12} sm={4} >
          <Box  sx={{ display: "flex", flexGrow: "1", justifyContent: "center" }}>
          <img
              src={aboutUs}
              alt="Assets"
              width="60%"
            />
            
          </Box>

        </Grid>
        <Grid item xs={12} sm={8} textAlign={{ xs: "center", sm: "left" }}>


          <Box p={2} sx={{}}>
            <h1 style={{ paddingBottom: "20px", borderBottom: "2px solid yellow", borderStyle: "outset" }}>About</h1>
            <p>
              The Earthereum Crystals is a collection of 8,888 unique ERC-721 tokens living on the Ethereum Blockchain. Each Crystal and it's backgrounds are 3D, generated by a custom-built algorithm and rendered via unbiased rendering with Artificial Intelligence.
              Each NFT is unique with Multiple traits which are all random AI generated NFTs. All the NFTs are locked on IPFS.<br />
            </p>
            <p>
              Well The digital world is here and everyone's got to have a NFT wallet in the future which is not so far.
              We wanted to create the First ever NFT project which will go on for multiple generations to come.
              Do you remember your grandmother's ring which is passed on to your mother/daughter/sister/girlfriend like a Family heirloom?
              Earthereum Crystals are the Family heirloom collection of unique NFTs and only 8,888 will ever exist.
            </p>
      
            <p>
              We Welcome you to The Earthereum Treasures Community.<br />
            </p>
            <p>
              Each NFT comes with a full membership to an ever-growing community and awesome utilities.
              Earthereum Treasures is an upcoming NFT Brand, we are a team with the same dream, to be at the Pinnacle of NFTs while supporting the cause of keeping Global Warming under control and reducing carbon footprints.
            </p>
            <p>
              We thank you for choosing Earthereum Treasures.
            </p>
         


          </Box>
        </Grid>
        

      </Grid>







    </section >
  );
};

export default About;
